name: Generate GitHub Contribution 🐍

on:
  schedule:         # Run automatically every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main         # Also run when pushing to main

jobs:
  generate-snake:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write   # Required to push to a branch

    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Hossam-elganainy
          outputs: dist/snake.svg?palette=github-dark

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
